# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lz7KR_Kue-XfyRPLqdG-n3kdgMus93UI
"""

!pip install langchain langchain-groq langchain-community chromadb sentence-transformers -q

import langchain
import chromadb
import sentence_transformers
print("All good")

policy_text = """
CUSTOMER SERVICE POLICY DOCUMENT
Company: FinServe Solutions

REFUND POLICY:
- Customers can request a refund within 30 days of purchase.
- Refunds are processed within 3-5 business days.
- Refunds are only applicable for failed transactions or duplicate charges.
- Customers must provide transaction ID and bank statement as proof.
- Refunds above 10,000 rupees require manager approval.

ACCOUNT SUSPENSION POLICY:
- Accounts are suspended after 3 consecutive failed login attempts.
- Suspended accounts can be reactivated by verifying government issued ID.
- Accounts inactive for more than 6 months are automatically suspended.
- Customers with outstanding dues cannot reactivate accounts until dues are cleared.

TRANSACTION DISPUTE POLICY:
- Disputes must be raised within 7 days of the transaction.
- Dispute resolution takes 5-10 business days.
- Customers will be notified via email at each stage of the dispute.
- If dispute is resolved in customer's favour, amount is credited within 2 business days.

CUSTOMER SUPPORT POLICY:
- Support is available 24/7 via chat and email.
- Phone support is available Monday to Friday, 9am to 6pm.
- Average response time for email is 24 hours.
- Priority support is available for premium customers.
"""

# Save it as a text file
with open("policy.txt", "w") as f:
    f.write(policy_text)

print("Document created.")

from langchain_community.document_loaders import TextLoader

loader = TextLoader("policy.txt")
documents = loader.load()

print(f"Loaded {len(documents)} document")
print(f"Characters: {len(documents[0].page_content)}")
print(f"Preview: {documents[0].page_content[:200]}")

!pip install langchain-text-splitters -q

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=200,
    chunk_overlap=50
)

chunks = splitter.split_documents(documents)

print(f"Total chunks: {len(chunks)}")
for i, chunk in enumerate(chunks):
    print(f"\nChunk {i+1}:")
    print(chunk.page_content)
    print("---")

!pip install langchain-huggingface -q

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Test it on a single sentence
test_vector = embeddings.embed_query("How do I get a refund?")

print(f"Vector length: {len(test_vector)}")
print(f"First 5 values: {test_vector[:5]}")

!pip install langchain-chroma -q

from langchain_chroma import Chroma

vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings
)

print(f"Stored {vectorstore._collection.count()} chunks in vector store")

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

query = "What is the refund policy?"
results = retriever.invoke(query)

print(f"Query: {query}\n")
for i, doc in enumerate(results):
    print(f"Result {i+1}:")
    print(doc.page_content)
    print("---")

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

llm = ChatGroq(
    api_key="api_key",
    model="llama-3.1-8b-instant"
)

prompt = ChatPromptTemplate.from_template("""
You are a helpful customer service agent for FinServe Solutions.
Answer the question based only on the context provided.
If the answer is not in the context, say "I don't have that information."

Context: {context}

Question: {question}
""")

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
)

response = rag_chain.invoke("What is the refund policy?")
print(response.content)

response = rag_chain.invoke("How do I reactivate my suspended account?")
print(response.content)

response = rag_chain.invoke("What are the loan interest rates?")
print(response.content)

from langchain_core.prompts import MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage

conversational_prompt = ChatPromptTemplate.from_messages([
    ("system", """You are a helpful customer service agent for FinServe Solutions.
Answer questions based only on the context provided.
If the answer is not in the context, say "I don't have that information." """),
    MessagesPlaceholder(variable_name="history"),
    ("human", "Context: {context}\n\nQuestion: {question}")
])

def chat_with_docs(question, history=[]):
    # Retrieve relevant chunks
    docs = retriever.invoke(question)
    context = format_docs(docs)

    # Build chain
    chain = conversational_prompt | llm

    # Invoke with history
    response = chain.invoke({
        "context": context,
        "question": question,
        "history": history
    })

    # Update history
    history.append(HumanMessage(content=question))
    history.append(AIMessage(content=response.content))

    return response.content, history

# Test it
history = []

response, history = chat_with_docs("What is the refund policy?", history)
print(f"User: What is the refund policy?")
print(f"Agent: {response}\n")

response, history = chat_with_docs("How long does it take?", history)
print(f"User: How long does it take?")
print(f"Agent: {response}\n")

response, history = chat_with_docs("What if the amount is above 10000 rupees?", history)
print(f"User: What if the amount is above 10000 rupees?")
print(f"Agent: {response}\n")

